title: Finding Non-Uniform Quantization Schemes using Multi-Task Gaussian Processes
description: Finding Non-Uniform Quantization Schemes using Multi-Task Gaussian Processes
url: nuq.active.vision
signoff: Marcelo Gennari Do Nascimento

links:
  - name: <strong>AVLCode</strong>
    url: https://code.active.vision
    external: true
  - name: <strong>GitHub</strong>
    url: https://github.com/ActiveVisionLab/NUQ
    external: true

permalink: pretty
